version: '3'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: transaction_db
      POSTGRES_USER: transaction_user
      POSTGRES_PASSWORD: transaction_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    command: python /app/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app  # Mounts the current directory to /app in the container
    ports:
      - "8080:8000"
    depends_on:
      - db

volumes:
  postgres_data:
